### PR TITLE
Add starter projects

### PR DESCRIPTION
**Pull request by hyperkineticnerd**
Add starter projects for a collection and a playbook/inventory

Should resolve Issue #15

### CODE REVIEW

**Comment by kyetter** [comment]
I'm not exactly sure what @jeffcpullen had in mind, but I think the idea would be to refactor the repo so that all of the 'starter project' parts are in the repo that you're adding (and removed from here) @hyperkineticnerd, also probably adding something to the read me so folks know where to find it. I could be way off base though!

**Comment by jeffcpullen** [comment]
So this is a good start and adding the starter projects is one part of the ask. 

I think the part that I wasn't explicit about but is important is moving the content that we have now into a separate repository. 

When I started trying to refactor the content we have now into a collection (which is not necessarily a requirement of this issue) I ran into the issue of the folder structure. Ansible is very particular in how collections need to be pathed. So having a starter project that imports a collection into a collections/ansible_collections/<project> would be a great example.

**Comment by hyperkineticnerd** [comment]
I may have been too excited to contribute as I don't see a way to use starter projects within devspaces.

**Comment by jeffcpullen** [comment]
What you have looks right (haven’t tested) regarding the starter project. 

@kyetter and I are only talking about how this repo needs to have the content here under /roles moved over to the target repo.

**Pull request closed without merging**
